FROM quay.io/minio/minio:RELEASE.2025-02-18T16-25-55Z

COPY init-buckets.sh /init-buckets.sh

RUN chmod +x /init-buckets.sh

ENTRYPOINT ["/bin/sh", "-c", "minio server /data --console-address ':9001' & sleep 10 && /init-buckets.sh"]